Repository OpenEnergyPlatform/open-MaStR, pull requests merged in 2023-01, with the labels that each got.

#405 Feature 403 SQLA 2 compatibility
  CHANGELOG.md
  open_mastr/soap_api/mirror.py
  open_mastr/xml_download/utils_write_to_database.py
  tests/xml_download/test_utils_write_to_database.py
Labels: :bug: bug

#407 Feature 406 bump2version
  .bumpversion.cfg
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  setup.py
Labels: :rocket: feature

#389 Improve ci pipline
  .github/workflows/ci-develop.yml
  .github/workflows/ci-production.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/test-pypi-publish.yml
  CHANGELOG.md
Labels: :rocket: feature

#401 Refactor csv export
  CHANGELOG.md
  open_mastr/mastr.py
  open_mastr/soap_api/download.py
  open_mastr/soap_api/metadata/create.py
  open_mastr/soap_api/mirror.py
  open_mastr/utils/config.py
  open_mastr/utils/constants.py
  open_mastr/utils/helpers.py
  open_mastr/utils/orm.py
  postprocessing/postprocessing.py
  scripts/mirror_mastr_csv_export.py
  scripts/utils/data_io.py
  tests/conftest.py
  tests/soap_api/test_mastr_mirror.py
  tests/test_helpers.py
Labels: :recycle: refactor

#422 Add check for bad Zip file #417
  CHANGELOG.md
  open_mastr/xml_download/utils_download_bulk.py
Labels: :rocket: feature

#421 Bugfix 420 csv export engine
  CHANGELOG.md
  open_mastr/utils/helpers.py
Labels: :bug: bug
